// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// AccountInfo2 is an object representing the database table.
type AccountInfo2 struct {
	CAccName            string      `boil:"cAccName" json:"cAccName" toml:"cAccName" yaml:"cAccName"`
	CSecPassWord        null.String `boil:"cSecPassWord" json:"cSecPassWord,omitempty" toml:"cSecPassWord" yaml:"cSecPassWord,omitempty"`
	CPassWord           string      `boil:"cPassWord" json:"cPassWord" toml:"cPassWord" yaml:"cPassWord"`
	IClientID           null.Int64  `boil:"iClientID" json:"iClientID,omitempty" toml:"iClientID" yaml:"iClientID,omitempty"`
	DLoginDate          null.Time   `boil:"dLoginDate" json:"dLoginDate,omitempty" toml:"dLoginDate" yaml:"dLoginDate,omitempty"`
	DLogoutDate         null.Time   `boil:"dLogoutDate" json:"dLogoutDate,omitempty" toml:"dLogoutDate" yaml:"dLogoutDate,omitempty"`
	NExtPoint           int16       `boil:"nExtPoint" json:"nExtPoint" toml:"nExtPoint" yaml:"nExtPoint"`
	NExtPoint1          int16       `boil:"nExtPoint1" json:"nExtPoint1" toml:"nExtPoint1" yaml:"nExtPoint1"`
	NExtPoint2          int16       `boil:"nExtPoint2" json:"nExtPoint2" toml:"nExtPoint2" yaml:"nExtPoint2"`
	NExtPoint3          int16       `boil:"nExtPoint3" json:"nExtPoint3" toml:"nExtPoint3" yaml:"nExtPoint3"`
	NExtPoint4          int16       `boil:"nExtPoint4" json:"nExtPoint4" toml:"nExtPoint4" yaml:"nExtPoint4"`
	NExtPoint5          int16       `boil:"nExtPoint5" json:"nExtPoint5" toml:"nExtPoint5" yaml:"nExtPoint5"`
	NExtPoint6          int16       `boil:"nExtPoint6" json:"nExtPoint6" toml:"nExtPoint6" yaml:"nExtPoint6"`
	NExtPoint7          int16       `boil:"nExtPoint7" json:"nExtPoint7" toml:"nExtPoint7" yaml:"nExtPoint7"`
	NUserIP             null.Int    `boil:"nUserIP" json:"nUserIP,omitempty" toml:"nUserIP" yaml:"nUserIP,omitempty"`
	NUserIPPort         null.Int    `boil:"nUserIPPort" json:"nUserIPPort,omitempty" toml:"nUserIPPort" yaml:"nUserIPPort,omitempty"`
	NFeeType            null.Int    `boil:"nFeeType" json:"nFeeType,omitempty" toml:"nFeeType" yaml:"nFeeType,omitempty"`
	BParentalControl    bool        `boil:"bParentalControl" json:"bParentalControl" toml:"bParentalControl" yaml:"bParentalControl"`
	BIsBanned           bool        `boil:"bIsBanned" json:"bIsBanned" toml:"bIsBanned" yaml:"bIsBanned"`
	BIsUseOTP           bool        `boil:"bIsUseOTP" json:"bIsUseOTP" toml:"bIsUseOTP" yaml:"bIsUseOTP"`
	IOTPSessionLifeTime int8        `boil:"iOTPSessionLifeTime" json:"iOTPSessionLifeTime" toml:"iOTPSessionLifeTime" yaml:"iOTPSessionLifeTime"`
	IServiceFlag        int         `boil:"iServiceFlag" json:"iServiceFlag" toml:"iServiceFlag" yaml:"iServiceFlag"`

	R *accountInfo2R `boil:"-" json:"-" toml:"-" yaml:"-"`
	L accountInfo2L  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AccountInfo2Columns = struct {
	CAccName            string
	CSecPassWord        string
	CPassWord           string
	IClientID           string
	DLoginDate          string
	DLogoutDate         string
	NExtPoint           string
	NExtPoint1          string
	NExtPoint2          string
	NExtPoint3          string
	NExtPoint4          string
	NExtPoint5          string
	NExtPoint6          string
	NExtPoint7          string
	NUserIP             string
	NUserIPPort         string
	NFeeType            string
	BParentalControl    string
	BIsBanned           string
	BIsUseOTP           string
	IOTPSessionLifeTime string
	IServiceFlag        string
}{
	CAccName:            "cAccName",
	CSecPassWord:        "cSecPassWord",
	CPassWord:           "cPassWord",
	IClientID:           "iClientID",
	DLoginDate:          "dLoginDate",
	DLogoutDate:         "dLogoutDate",
	NExtPoint:           "nExtPoint",
	NExtPoint1:          "nExtPoint1",
	NExtPoint2:          "nExtPoint2",
	NExtPoint3:          "nExtPoint3",
	NExtPoint4:          "nExtPoint4",
	NExtPoint5:          "nExtPoint5",
	NExtPoint6:          "nExtPoint6",
	NExtPoint7:          "nExtPoint7",
	NUserIP:             "nUserIP",
	NUserIPPort:         "nUserIPPort",
	NFeeType:            "nFeeType",
	BParentalControl:    "bParentalControl",
	BIsBanned:           "bIsBanned",
	BIsUseOTP:           "bIsUseOTP",
	IOTPSessionLifeTime: "iOTPSessionLifeTime",
	IServiceFlag:        "iServiceFlag",
}

var AccountInfo2TableColumns = struct {
	CAccName            string
	CSecPassWord        string
	CPassWord           string
	IClientID           string
	DLoginDate          string
	DLogoutDate         string
	NExtPoint           string
	NExtPoint1          string
	NExtPoint2          string
	NExtPoint3          string
	NExtPoint4          string
	NExtPoint5          string
	NExtPoint6          string
	NExtPoint7          string
	NUserIP             string
	NUserIPPort         string
	NFeeType            string
	BParentalControl    string
	BIsBanned           string
	BIsUseOTP           string
	IOTPSessionLifeTime string
	IServiceFlag        string
}{
	CAccName:            "Account_Info2.cAccName",
	CSecPassWord:        "Account_Info2.cSecPassWord",
	CPassWord:           "Account_Info2.cPassWord",
	IClientID:           "Account_Info2.iClientID",
	DLoginDate:          "Account_Info2.dLoginDate",
	DLogoutDate:         "Account_Info2.dLogoutDate",
	NExtPoint:           "Account_Info2.nExtPoint",
	NExtPoint1:          "Account_Info2.nExtPoint1",
	NExtPoint2:          "Account_Info2.nExtPoint2",
	NExtPoint3:          "Account_Info2.nExtPoint3",
	NExtPoint4:          "Account_Info2.nExtPoint4",
	NExtPoint5:          "Account_Info2.nExtPoint5",
	NExtPoint6:          "Account_Info2.nExtPoint6",
	NExtPoint7:          "Account_Info2.nExtPoint7",
	NUserIP:             "Account_Info2.nUserIP",
	NUserIPPort:         "Account_Info2.nUserIPPort",
	NFeeType:            "Account_Info2.nFeeType",
	BParentalControl:    "Account_Info2.bParentalControl",
	BIsBanned:           "Account_Info2.bIsBanned",
	BIsUseOTP:           "Account_Info2.bIsUseOTP",
	IOTPSessionLifeTime: "Account_Info2.iOTPSessionLifeTime",
	IServiceFlag:        "Account_Info2.iServiceFlag",
}

// Generated where

var AccountInfo2Where = struct {
	CAccName            whereHelperstring
	CSecPassWord        whereHelpernull_String
	CPassWord           whereHelperstring
	IClientID           whereHelpernull_Int64
	DLoginDate          whereHelpernull_Time
	DLogoutDate         whereHelpernull_Time
	NExtPoint           whereHelperint16
	NExtPoint1          whereHelperint16
	NExtPoint2          whereHelperint16
	NExtPoint3          whereHelperint16
	NExtPoint4          whereHelperint16
	NExtPoint5          whereHelperint16
	NExtPoint6          whereHelperint16
	NExtPoint7          whereHelperint16
	NUserIP             whereHelpernull_Int
	NUserIPPort         whereHelpernull_Int
	NFeeType            whereHelpernull_Int
	BParentalControl    whereHelperbool
	BIsBanned           whereHelperbool
	BIsUseOTP           whereHelperbool
	IOTPSessionLifeTime whereHelperint8
	IServiceFlag        whereHelperint
}{
	CAccName:            whereHelperstring{field: "[dbo].[Account_Info2].[cAccName]"},
	CSecPassWord:        whereHelpernull_String{field: "[dbo].[Account_Info2].[cSecPassWord]"},
	CPassWord:           whereHelperstring{field: "[dbo].[Account_Info2].[cPassWord]"},
	IClientID:           whereHelpernull_Int64{field: "[dbo].[Account_Info2].[iClientID]"},
	DLoginDate:          whereHelpernull_Time{field: "[dbo].[Account_Info2].[dLoginDate]"},
	DLogoutDate:         whereHelpernull_Time{field: "[dbo].[Account_Info2].[dLogoutDate]"},
	NExtPoint:           whereHelperint16{field: "[dbo].[Account_Info2].[nExtPoint]"},
	NExtPoint1:          whereHelperint16{field: "[dbo].[Account_Info2].[nExtPoint1]"},
	NExtPoint2:          whereHelperint16{field: "[dbo].[Account_Info2].[nExtPoint2]"},
	NExtPoint3:          whereHelperint16{field: "[dbo].[Account_Info2].[nExtPoint3]"},
	NExtPoint4:          whereHelperint16{field: "[dbo].[Account_Info2].[nExtPoint4]"},
	NExtPoint5:          whereHelperint16{field: "[dbo].[Account_Info2].[nExtPoint5]"},
	NExtPoint6:          whereHelperint16{field: "[dbo].[Account_Info2].[nExtPoint6]"},
	NExtPoint7:          whereHelperint16{field: "[dbo].[Account_Info2].[nExtPoint7]"},
	NUserIP:             whereHelpernull_Int{field: "[dbo].[Account_Info2].[nUserIP]"},
	NUserIPPort:         whereHelpernull_Int{field: "[dbo].[Account_Info2].[nUserIPPort]"},
	NFeeType:            whereHelpernull_Int{field: "[dbo].[Account_Info2].[nFeeType]"},
	BParentalControl:    whereHelperbool{field: "[dbo].[Account_Info2].[bParentalControl]"},
	BIsBanned:           whereHelperbool{field: "[dbo].[Account_Info2].[bIsBanned]"},
	BIsUseOTP:           whereHelperbool{field: "[dbo].[Account_Info2].[bIsUseOTP]"},
	IOTPSessionLifeTime: whereHelperint8{field: "[dbo].[Account_Info2].[iOTPSessionLifeTime]"},
	IServiceFlag:        whereHelperint{field: "[dbo].[Account_Info2].[iServiceFlag]"},
}

// AccountInfo2Rels is where relationship names are stored.
var AccountInfo2Rels = struct {
}{}

// accountInfo2R is where relationships are stored.
type accountInfo2R struct {
}

// NewStruct creates a new relationship struct
func (*accountInfo2R) NewStruct() *accountInfo2R {
	return &accountInfo2R{}
}

// accountInfo2L is where Load methods for each relationship are stored.
type accountInfo2L struct{}

var (
	accountInfo2AllColumns            = []string{"cAccName", "cSecPassWord", "cPassWord", "iClientID", "dLoginDate", "dLogoutDate", "nExtPoint", "nExtPoint1", "nExtPoint2", "nExtPoint3", "nExtPoint4", "nExtPoint5", "nExtPoint6", "nExtPoint7", "nUserIP", "nUserIPPort", "nFeeType", "bParentalControl", "bIsBanned", "bIsUseOTP", "iOTPSessionLifeTime", "iServiceFlag"}
	accountInfo2ColumnsWithoutDefault = []string{"cAccName", "cSecPassWord", "cPassWord", "iClientID", "dLoginDate", "dLogoutDate", "nExtPoint", "nExtPoint1", "nExtPoint2", "nExtPoint3", "nExtPoint4", "nExtPoint5", "nExtPoint6", "nExtPoint7", "nUserIP", "nUserIPPort", "nFeeType"}
	accountInfo2ColumnsWithDefault    = []string{"bParentalControl", "bIsBanned", "bIsUseOTP", "iOTPSessionLifeTime", "iServiceFlag"}
	accountInfo2PrimaryKeyColumns     = []string{"cAccName"}
	accountInfo2GeneratedColumns      = []string{}
)

type (
	// AccountInfo2Slice is an alias for a slice of pointers to AccountInfo2.
	// This should almost always be used instead of []AccountInfo2.
	AccountInfo2Slice []*AccountInfo2

	accountInfo2Query struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	accountInfo2Type                 = reflect.TypeOf(&AccountInfo2{})
	accountInfo2Mapping              = queries.MakeStructMapping(accountInfo2Type)
	accountInfo2PrimaryKeyMapping, _ = queries.BindMapping(accountInfo2Type, accountInfo2Mapping, accountInfo2PrimaryKeyColumns)
	accountInfo2InsertCacheMut       sync.RWMutex
	accountInfo2InsertCache          = make(map[string]insertCache)
	accountInfo2UpdateCacheMut       sync.RWMutex
	accountInfo2UpdateCache          = make(map[string]updateCache)
	accountInfo2UpsertCacheMut       sync.RWMutex
	accountInfo2UpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single accountInfo2 record from the query.
func (q accountInfo2Query) One(ctx context.Context, exec boil.ContextExecutor) (*AccountInfo2, error) {
	o := &AccountInfo2{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for Account_Info2")
	}

	return o, nil
}

// All returns all AccountInfo2 records from the query.
func (q accountInfo2Query) All(ctx context.Context, exec boil.ContextExecutor) (AccountInfo2Slice, error) {
	var o []*AccountInfo2

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to AccountInfo2 slice")
	}

	return o, nil
}

// Count returns the count of all AccountInfo2 records in the query.
func (q accountInfo2Query) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count Account_Info2 rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q accountInfo2Query) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if Account_Info2 exists")
	}

	return count > 0, nil
}

// AccountInfo2s retrieves all the records using an executor.
func AccountInfo2s(mods ...qm.QueryMod) accountInfo2Query {
	mods = append(mods, qm.From("[dbo].[Account_Info2]"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"[dbo].[Account_Info2].*"})
	}

	return accountInfo2Query{q}
}

// FindAccountInfo2 retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAccountInfo2(ctx context.Context, exec boil.ContextExecutor, cAccName string, selectCols ...string) (*AccountInfo2, error) {
	accountInfo2Obj := &AccountInfo2{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from [dbo].[Account_Info2] where [cAccName]=$1", sel,
	)

	q := queries.Raw(query, cAccName)

	err := q.Bind(ctx, exec, accountInfo2Obj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from Account_Info2")
	}

	return accountInfo2Obj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *AccountInfo2) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no Account_Info2 provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(accountInfo2ColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	accountInfo2InsertCacheMut.RLock()
	cache, cached := accountInfo2InsertCache[key]
	accountInfo2InsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			accountInfo2AllColumns,
			accountInfo2ColumnsWithDefault,
			accountInfo2ColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(accountInfo2Type, accountInfo2Mapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(accountInfo2Type, accountInfo2Mapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO [dbo].[Account_Info2] ([%s]) %%sVALUES (%s)%%s", strings.Join(wl, "],["), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO [dbo].[Account_Info2] %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryOutput = fmt.Sprintf("OUTPUT INSERTED.[%s] ", strings.Join(returnColumns, "],INSERTED.["))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into Account_Info2")
	}

	if !cached {
		accountInfo2InsertCacheMut.Lock()
		accountInfo2InsertCache[key] = cache
		accountInfo2InsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the AccountInfo2.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *AccountInfo2) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	accountInfo2UpdateCacheMut.RLock()
	cache, cached := accountInfo2UpdateCache[key]
	accountInfo2UpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			accountInfo2AllColumns,
			accountInfo2PrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update Account_Info2, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE [dbo].[Account_Info2] SET %s WHERE %s",
			strmangle.SetParamNames("[", "]", 1, wl),
			strmangle.WhereClause("[", "]", len(wl)+1, accountInfo2PrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(accountInfo2Type, accountInfo2Mapping, append(wl, accountInfo2PrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update Account_Info2 row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for Account_Info2")
	}

	if !cached {
		accountInfo2UpdateCacheMut.Lock()
		accountInfo2UpdateCache[key] = cache
		accountInfo2UpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q accountInfo2Query) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for Account_Info2")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for Account_Info2")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AccountInfo2Slice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountInfo2PrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE [dbo].[Account_Info2] SET %s WHERE %s",
		strmangle.SetParamNames("[", "]", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, accountInfo2PrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in accountInfo2 slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all accountInfo2")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *AccountInfo2) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no Account_Info2 provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(accountInfo2ColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	accountInfo2UpsertCacheMut.RLock()
	cache, cached := accountInfo2UpsertCache[key]
	accountInfo2UpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			accountInfo2AllColumns,
			accountInfo2ColumnsWithDefault,
			accountInfo2ColumnsWithoutDefault,
			nzDefaults,
		)

		for i, v := range insert {
			if strmangle.ContainsAny(accountInfo2PrimaryKeyColumns, v) && strmangle.ContainsAny(accountInfo2ColumnsWithDefault, v) {
				insert = append(insert[:i], insert[i+1:]...)
			}
		}
		if len(insert) == 0 {
			return errors.New("models: unable to upsert Account_Info2, could not build insert column list")
		}

		update := updateColumns.UpdateColumnSet(
			accountInfo2AllColumns,
			accountInfo2PrimaryKeyColumns,
		)

		ret := strmangle.SetComplement(accountInfo2AllColumns, strmangle.SetIntersect(insert, update))

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert Account_Info2, could not build update column list")
		}

		cache.query = buildUpsertQueryMSSQL(dialect, "[dbo].[Account_Info2]", accountInfo2PrimaryKeyColumns, update, insert, ret)

		whitelist := make([]string, len(accountInfo2PrimaryKeyColumns))
		copy(whitelist, accountInfo2PrimaryKeyColumns)
		whitelist = append(whitelist, update...)
		whitelist = append(whitelist, insert...)

		cache.valueMapping, err = queries.BindMapping(accountInfo2Type, accountInfo2Mapping, whitelist)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(accountInfo2Type, accountInfo2Mapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // MSSQL doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert Account_Info2")
	}

	if !cached {
		accountInfo2UpsertCacheMut.Lock()
		accountInfo2UpsertCache[key] = cache
		accountInfo2UpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single AccountInfo2 record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *AccountInfo2) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no AccountInfo2 provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), accountInfo2PrimaryKeyMapping)
	sql := "DELETE FROM [dbo].[Account_Info2] WHERE [cAccName]=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from Account_Info2")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for Account_Info2")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q accountInfo2Query) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no accountInfo2Query provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from Account_Info2")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for Account_Info2")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AccountInfo2Slice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountInfo2PrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM [dbo].[Account_Info2] WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, accountInfo2PrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from accountInfo2 slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for Account_Info2")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *AccountInfo2) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindAccountInfo2(ctx, exec, o.CAccName)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AccountInfo2Slice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := AccountInfo2Slice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountInfo2PrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT [dbo].[Account_Info2].* FROM [dbo].[Account_Info2] WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, accountInfo2PrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in AccountInfo2Slice")
	}

	*o = slice

	return nil
}

// AccountInfo2Exists checks if the AccountInfo2 row exists.
func AccountInfo2Exists(ctx context.Context, exec boil.ContextExecutor, cAccName string) (bool, error) {
	var exists bool
	sql := "select case when exists(select top(1) 1 from [dbo].[Account_Info2] where [cAccName]=$1) then 1 else 0 end"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, cAccName)
	}
	row := exec.QueryRowContext(ctx, sql, cAccName)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if Account_Info2 exists")
	}

	return exists, nil
}

// Exists checks if the AccountInfo2 row exists.
func (o *AccountInfo2) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return AccountInfo2Exists(ctx, exec, o.CAccName)
}
