// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// AccountHabitus is an object representing the database table.
type AccountHabitus struct {
	CAccName    string    `boil:"cAccName" json:"cAccName" toml:"cAccName" yaml:"cAccName"`
	ILeftSecond null.Int  `boil:"iLeftSecond" json:"iLeftSecond,omitempty" toml:"iLeftSecond" yaml:"iLeftSecond,omitempty"`
	DEndDate    time.Time `boil:"dEndDate" json:"dEndDate" toml:"dEndDate" yaml:"dEndDate"`
	IUseSecond  null.Int  `boil:"iUseSecond" json:"iUseSecond,omitempty" toml:"iUseSecond" yaml:"iUseSecond,omitempty"`

	R *accountHabitusR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L accountHabitusL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AccountHabitusColumns = struct {
	CAccName    string
	ILeftSecond string
	DEndDate    string
	IUseSecond  string
}{
	CAccName:    "cAccName",
	ILeftSecond: "iLeftSecond",
	DEndDate:    "dEndDate",
	IUseSecond:  "iUseSecond",
}

var AccountHabitusTableColumns = struct {
	CAccName    string
	ILeftSecond string
	DEndDate    string
	IUseSecond  string
}{
	CAccName:    "Account_Habitus.cAccName",
	ILeftSecond: "Account_Habitus.iLeftSecond",
	DEndDate:    "Account_Habitus.dEndDate",
	IUseSecond:  "Account_Habitus.iUseSecond",
}

// Generated where

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod    { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod   { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod    { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod   { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod    { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod   { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) LIKE(x string) qm.QueryMod  { return qm.Where(w.field+" LIKE ?", x) }
func (w whereHelperstring) NLIKE(x string) qm.QueryMod { return qm.Where(w.field+" NOT LIKE ?", x) }
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpernull_Int struct{ field string }

func (w whereHelpernull_Int) EQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Int) NEQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Int) LT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Int) LTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Int) GT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Int) GTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_Int) IN(slice []int) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_Int) NIN(slice []int) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_Int) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Int) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelpertime_Time struct{ field string }

func (w whereHelpertime_Time) EQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertime_Time) NEQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertime_Time) LT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertime_Time) LTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertime_Time) GT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertime_Time) GTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var AccountHabitusWhere = struct {
	CAccName    whereHelperstring
	ILeftSecond whereHelpernull_Int
	DEndDate    whereHelpertime_Time
	IUseSecond  whereHelpernull_Int
}{
	CAccName:    whereHelperstring{field: "[dbo].[Account_Habitus].[cAccName]"},
	ILeftSecond: whereHelpernull_Int{field: "[dbo].[Account_Habitus].[iLeftSecond]"},
	DEndDate:    whereHelpertime_Time{field: "[dbo].[Account_Habitus].[dEndDate]"},
	IUseSecond:  whereHelpernull_Int{field: "[dbo].[Account_Habitus].[iUseSecond]"},
}

// AccountHabitusRels is where relationship names are stored.
var AccountHabitusRels = struct {
}{}

// accountHabitusR is where relationships are stored.
type accountHabitusR struct {
}

// NewStruct creates a new relationship struct
func (*accountHabitusR) NewStruct() *accountHabitusR {
	return &accountHabitusR{}
}

// accountHabitusL is where Load methods for each relationship are stored.
type accountHabitusL struct{}

var (
	accountHabitusAllColumns            = []string{"cAccName", "iLeftSecond", "dEndDate", "iUseSecond"}
	accountHabitusColumnsWithoutDefault = []string{"cAccName", "iLeftSecond", "dEndDate", "iUseSecond"}
	accountHabitusColumnsWithDefault    = []string{}
	accountHabitusPrimaryKeyColumns     = []string{"cAccName"}
	accountHabitusGeneratedColumns      = []string{}
)

type (
	// AccountHabitusSlice is an alias for a slice of pointers to AccountHabitus.
	// This should almost always be used instead of []AccountHabitus.
	AccountHabitusSlice []*AccountHabitus

	accountHabitusQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	accountHabitusType                 = reflect.TypeOf(&AccountHabitus{})
	accountHabitusMapping              = queries.MakeStructMapping(accountHabitusType)
	accountHabitusPrimaryKeyMapping, _ = queries.BindMapping(accountHabitusType, accountHabitusMapping, accountHabitusPrimaryKeyColumns)
	accountHabitusInsertCacheMut       sync.RWMutex
	accountHabitusInsertCache          = make(map[string]insertCache)
	accountHabitusUpdateCacheMut       sync.RWMutex
	accountHabitusUpdateCache          = make(map[string]updateCache)
	accountHabitusUpsertCacheMut       sync.RWMutex
	accountHabitusUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single accountHabitus record from the query.
func (q accountHabitusQuery) One(ctx context.Context, exec boil.ContextExecutor) (*AccountHabitus, error) {
	o := &AccountHabitus{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for Account_Habitus")
	}

	return o, nil
}

// All returns all AccountHabitus records from the query.
func (q accountHabitusQuery) All(ctx context.Context, exec boil.ContextExecutor) (AccountHabitusSlice, error) {
	var o []*AccountHabitus

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to AccountHabitus slice")
	}

	return o, nil
}

// Count returns the count of all AccountHabitus records in the query.
func (q accountHabitusQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count Account_Habitus rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q accountHabitusQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if Account_Habitus exists")
	}

	return count > 0, nil
}

// AccountHabitus retrieves all the records using an executor.
func AccountHabituses(mods ...qm.QueryMod) accountHabitusQuery {
	mods = append(mods, qm.From("[dbo].[Account_Habitus]"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"[dbo].[Account_Habitus].*"})
	}

	return accountHabitusQuery{q}
}

// FindAccountHabitus retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAccountHabitus(ctx context.Context, exec boil.ContextExecutor, cAccName string, selectCols ...string) (*AccountHabitus, error) {
	accountHabitusObj := &AccountHabitus{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from [dbo].[Account_Habitus] where [cAccName]=$1", sel,
	)

	q := queries.Raw(query, cAccName)

	err := q.Bind(ctx, exec, accountHabitusObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from Account_Habitus")
	}

	return accountHabitusObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *AccountHabitus) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no Account_Habitus provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(accountHabitusColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	accountHabitusInsertCacheMut.RLock()
	cache, cached := accountHabitusInsertCache[key]
	accountHabitusInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			accountHabitusAllColumns,
			accountHabitusColumnsWithDefault,
			accountHabitusColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(accountHabitusType, accountHabitusMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(accountHabitusType, accountHabitusMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO [dbo].[Account_Habitus] ([%s]) %%sVALUES (%s)%%s", strings.Join(wl, "],["), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO [dbo].[Account_Habitus] %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryOutput = fmt.Sprintf("OUTPUT INSERTED.[%s] ", strings.Join(returnColumns, "],INSERTED.["))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into Account_Habitus")
	}

	if !cached {
		accountHabitusInsertCacheMut.Lock()
		accountHabitusInsertCache[key] = cache
		accountHabitusInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the AccountHabitus.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *AccountHabitus) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	accountHabitusUpdateCacheMut.RLock()
	cache, cached := accountHabitusUpdateCache[key]
	accountHabitusUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			accountHabitusAllColumns,
			accountHabitusPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update Account_Habitus, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE [dbo].[Account_Habitus] SET %s WHERE %s",
			strmangle.SetParamNames("[", "]", 1, wl),
			strmangle.WhereClause("[", "]", len(wl)+1, accountHabitusPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(accountHabitusType, accountHabitusMapping, append(wl, accountHabitusPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update Account_Habitus row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for Account_Habitus")
	}

	if !cached {
		accountHabitusUpdateCacheMut.Lock()
		accountHabitusUpdateCache[key] = cache
		accountHabitusUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q accountHabitusQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for Account_Habitus")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for Account_Habitus")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AccountHabitusSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountHabitusPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE [dbo].[Account_Habitus] SET %s WHERE %s",
		strmangle.SetParamNames("[", "]", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, accountHabitusPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in accountHabitus slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all accountHabitus")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *AccountHabitus) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no Account_Habitus provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(accountHabitusColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	accountHabitusUpsertCacheMut.RLock()
	cache, cached := accountHabitusUpsertCache[key]
	accountHabitusUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			accountHabitusAllColumns,
			accountHabitusColumnsWithDefault,
			accountHabitusColumnsWithoutDefault,
			nzDefaults,
		)

		for i, v := range insert {
			if strmangle.ContainsAny(accountHabitusPrimaryKeyColumns, v) && strmangle.ContainsAny(accountHabitusColumnsWithDefault, v) {
				insert = append(insert[:i], insert[i+1:]...)
			}
		}
		if len(insert) == 0 {
			return errors.New("models: unable to upsert Account_Habitus, could not build insert column list")
		}

		update := updateColumns.UpdateColumnSet(
			accountHabitusAllColumns,
			accountHabitusPrimaryKeyColumns,
		)

		ret := strmangle.SetComplement(accountHabitusAllColumns, strmangle.SetIntersect(insert, update))

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert Account_Habitus, could not build update column list")
		}

		cache.query = buildUpsertQueryMSSQL(dialect, "[dbo].[Account_Habitus]", accountHabitusPrimaryKeyColumns, update, insert, ret)

		whitelist := make([]string, len(accountHabitusPrimaryKeyColumns))
		copy(whitelist, accountHabitusPrimaryKeyColumns)
		whitelist = append(whitelist, update...)
		whitelist = append(whitelist, insert...)

		cache.valueMapping, err = queries.BindMapping(accountHabitusType, accountHabitusMapping, whitelist)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(accountHabitusType, accountHabitusMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // MSSQL doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert Account_Habitus")
	}

	if !cached {
		accountHabitusUpsertCacheMut.Lock()
		accountHabitusUpsertCache[key] = cache
		accountHabitusUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single AccountHabitus record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *AccountHabitus) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no AccountHabitus provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), accountHabitusPrimaryKeyMapping)
	sql := "DELETE FROM [dbo].[Account_Habitus] WHERE [cAccName]=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from Account_Habitus")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for Account_Habitus")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q accountHabitusQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no accountHabitusQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from Account_Habitus")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for Account_Habitus")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AccountHabitusSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountHabitusPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM [dbo].[Account_Habitus] WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, accountHabitusPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from accountHabitus slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for Account_Habitus")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *AccountHabitus) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindAccountHabitus(ctx, exec, o.CAccName)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AccountHabitusSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := AccountHabitusSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountHabitusPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT [dbo].[Account_Habitus].* FROM [dbo].[Account_Habitus] WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, accountHabitusPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in AccountHabitusSlice")
	}

	*o = slice

	return nil
}

// AccountHabitusExists checks if the AccountHabitus row exists.
func AccountHabitusExists(ctx context.Context, exec boil.ContextExecutor, cAccName string) (bool, error) {
	var exists bool
	sql := "select case when exists(select top(1) 1 from [dbo].[Account_Habitus] where [cAccName]=$1) then 1 else 0 end"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, cAccName)
	}
	row := exec.QueryRowContext(ctx, sql, cAccName)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if Account_Habitus exists")
	}

	return exists, nil
}

// Exists checks if the AccountHabitus row exists.
func (o *AccountHabitus) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return AccountHabitusExists(ctx, exec, o.CAccName)
}
