// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// AccountInfo is an object representing the database table.
type AccountInfo struct {
	CAccName            string      `boil:"cAccName" json:"cAccName" toml:"cAccName" yaml:"cAccName"`
	CSecPassWord        null.String `boil:"cSecPassWord" json:"cSecPassWord,omitempty" toml:"cSecPassWord" yaml:"cSecPassWord,omitempty"`
	CPassWord           string      `boil:"cPassWord" json:"cPassWord" toml:"cPassWord" yaml:"cPassWord"`
	IClientID           null.Int64  `boil:"iClientID" json:"iClientID,omitempty" toml:"iClientID" yaml:"iClientID,omitempty"`
	DLoginDate          null.Time   `boil:"dLoginDate" json:"dLoginDate,omitempty" toml:"dLoginDate" yaml:"dLoginDate,omitempty"`
	DLogoutDate         null.Time   `boil:"dLogoutDate" json:"dLogoutDate,omitempty" toml:"dLogoutDate" yaml:"dLogoutDate,omitempty"`
	NExtPoint           int16       `boil:"nExtPoint" json:"nExtPoint" toml:"nExtPoint" yaml:"nExtPoint"`
	NExtPoint1          int16       `boil:"nExtPoint1" json:"nExtPoint1" toml:"nExtPoint1" yaml:"nExtPoint1"`
	NExtPoint2          int16       `boil:"nExtPoint2" json:"nExtPoint2" toml:"nExtPoint2" yaml:"nExtPoint2"`
	NExtPoint3          int16       `boil:"nExtPoint3" json:"nExtPoint3" toml:"nExtPoint3" yaml:"nExtPoint3"`
	NExtPoint4          int16       `boil:"nExtPoint4" json:"nExtPoint4" toml:"nExtPoint4" yaml:"nExtPoint4"`
	NExtPoint5          int16       `boil:"nExtPoint5" json:"nExtPoint5" toml:"nExtPoint5" yaml:"nExtPoint5"`
	NExtPoint6          int16       `boil:"nExtPoint6" json:"nExtPoint6" toml:"nExtPoint6" yaml:"nExtPoint6"`
	NExtPoint7          int16       `boil:"nExtPoint7" json:"nExtPoint7" toml:"nExtPoint7" yaml:"nExtPoint7"`
	NUserIP             null.Int    `boil:"nUserIP" json:"nUserIP,omitempty" toml:"nUserIP" yaml:"nUserIP,omitempty"`
	NUserIPPort         null.Int    `boil:"nUserIPPort" json:"nUserIPPort,omitempty" toml:"nUserIPPort" yaml:"nUserIPPort,omitempty"`
	NFeeType            null.Int    `boil:"nFeeType" json:"nFeeType,omitempty" toml:"nFeeType" yaml:"nFeeType,omitempty"`
	BParentalControl    bool        `boil:"bParentalControl" json:"bParentalControl" toml:"bParentalControl" yaml:"bParentalControl"`
	BIsBanned           bool        `boil:"bIsBanned" json:"bIsBanned" toml:"bIsBanned" yaml:"bIsBanned"`
	BIsUseOTP           bool        `boil:"bIsUseOTP" json:"bIsUseOTP" toml:"bIsUseOTP" yaml:"bIsUseOTP"`
	IOTPSessionLifeTime int8        `boil:"iOTPSessionLifeTime" json:"iOTPSessionLifeTime" toml:"iOTPSessionLifeTime" yaml:"iOTPSessionLifeTime"`
	IServiceFlag        int         `boil:"iServiceFlag" json:"iServiceFlag" toml:"iServiceFlag" yaml:"iServiceFlag"`

	R *accountInfoR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L accountInfoL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AccountInfoColumns = struct {
	CAccName            string
	CSecPassWord        string
	CPassWord           string
	IClientID           string
	DLoginDate          string
	DLogoutDate         string
	NExtPoint           string
	NExtPoint1          string
	NExtPoint2          string
	NExtPoint3          string
	NExtPoint4          string
	NExtPoint5          string
	NExtPoint6          string
	NExtPoint7          string
	NUserIP             string
	NUserIPPort         string
	NFeeType            string
	BParentalControl    string
	BIsBanned           string
	BIsUseOTP           string
	IOTPSessionLifeTime string
	IServiceFlag        string
}{
	CAccName:            "cAccName",
	CSecPassWord:        "cSecPassWord",
	CPassWord:           "cPassWord",
	IClientID:           "iClientID",
	DLoginDate:          "dLoginDate",
	DLogoutDate:         "dLogoutDate",
	NExtPoint:           "nExtPoint",
	NExtPoint1:          "nExtPoint1",
	NExtPoint2:          "nExtPoint2",
	NExtPoint3:          "nExtPoint3",
	NExtPoint4:          "nExtPoint4",
	NExtPoint5:          "nExtPoint5",
	NExtPoint6:          "nExtPoint6",
	NExtPoint7:          "nExtPoint7",
	NUserIP:             "nUserIP",
	NUserIPPort:         "nUserIPPort",
	NFeeType:            "nFeeType",
	BParentalControl:    "bParentalControl",
	BIsBanned:           "bIsBanned",
	BIsUseOTP:           "bIsUseOTP",
	IOTPSessionLifeTime: "iOTPSessionLifeTime",
	IServiceFlag:        "iServiceFlag",
}

var AccountInfoTableColumns = struct {
	CAccName            string
	CSecPassWord        string
	CPassWord           string
	IClientID           string
	DLoginDate          string
	DLogoutDate         string
	NExtPoint           string
	NExtPoint1          string
	NExtPoint2          string
	NExtPoint3          string
	NExtPoint4          string
	NExtPoint5          string
	NExtPoint6          string
	NExtPoint7          string
	NUserIP             string
	NUserIPPort         string
	NFeeType            string
	BParentalControl    string
	BIsBanned           string
	BIsUseOTP           string
	IOTPSessionLifeTime string
	IServiceFlag        string
}{
	CAccName:            "Account_Info.cAccName",
	CSecPassWord:        "Account_Info.cSecPassWord",
	CPassWord:           "Account_Info.cPassWord",
	IClientID:           "Account_Info.iClientID",
	DLoginDate:          "Account_Info.dLoginDate",
	DLogoutDate:         "Account_Info.dLogoutDate",
	NExtPoint:           "Account_Info.nExtPoint",
	NExtPoint1:          "Account_Info.nExtPoint1",
	NExtPoint2:          "Account_Info.nExtPoint2",
	NExtPoint3:          "Account_Info.nExtPoint3",
	NExtPoint4:          "Account_Info.nExtPoint4",
	NExtPoint5:          "Account_Info.nExtPoint5",
	NExtPoint6:          "Account_Info.nExtPoint6",
	NExtPoint7:          "Account_Info.nExtPoint7",
	NUserIP:             "Account_Info.nUserIP",
	NUserIPPort:         "Account_Info.nUserIPPort",
	NFeeType:            "Account_Info.nFeeType",
	BParentalControl:    "Account_Info.bParentalControl",
	BIsBanned:           "Account_Info.bIsBanned",
	BIsUseOTP:           "Account_Info.bIsUseOTP",
	IOTPSessionLifeTime: "Account_Info.iOTPSessionLifeTime",
	IServiceFlag:        "Account_Info.iServiceFlag",
}

// Generated where

type whereHelpernull_String struct{ field string }

func (w whereHelpernull_String) EQ(x null.String) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_String) NEQ(x null.String) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_String) LT(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_String) LTE(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_String) GT(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_String) GTE(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_String) LIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" LIKE ?", x)
}
func (w whereHelpernull_String) NLIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT LIKE ?", x)
}
func (w whereHelpernull_String) IN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_String) NIN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_String) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_String) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelpernull_Int64 struct{ field string }

func (w whereHelpernull_Int64) EQ(x null.Int64) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Int64) NEQ(x null.Int64) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Int64) LT(x null.Int64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Int64) LTE(x null.Int64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Int64) GT(x null.Int64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Int64) GTE(x null.Int64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_Int64) IN(slice []int64) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_Int64) NIN(slice []int64) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_Int64) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Int64) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelpernull_Time struct{ field string }

func (w whereHelpernull_Time) EQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Time) NEQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Time) LT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Time) LTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Time) GT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Time) GTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpernull_Time) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Time) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelperint16 struct{ field string }

func (w whereHelperint16) EQ(x int16) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint16) NEQ(x int16) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint16) LT(x int16) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint16) LTE(x int16) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint16) GT(x int16) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint16) GTE(x int16) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint16) IN(slice []int16) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint16) NIN(slice []int16) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelperbool struct{ field string }

func (w whereHelperbool) EQ(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperbool) NEQ(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperbool) LT(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperbool) LTE(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperbool) GT(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperbool) GTE(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }

type whereHelperint8 struct{ field string }

func (w whereHelperint8) EQ(x int8) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint8) NEQ(x int8) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint8) LT(x int8) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint8) LTE(x int8) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint8) GT(x int8) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint8) GTE(x int8) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint8) IN(slice []int8) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint8) NIN(slice []int8) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelperint struct{ field string }

func (w whereHelperint) EQ(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint) NEQ(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint) LT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint) LTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint) GT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint) GTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint) IN(slice []int) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint) NIN(slice []int) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var AccountInfoWhere = struct {
	CAccName            whereHelperstring
	CSecPassWord        whereHelpernull_String
	CPassWord           whereHelperstring
	IClientID           whereHelpernull_Int64
	DLoginDate          whereHelpernull_Time
	DLogoutDate         whereHelpernull_Time
	NExtPoint           whereHelperint16
	NExtPoint1          whereHelperint16
	NExtPoint2          whereHelperint16
	NExtPoint3          whereHelperint16
	NExtPoint4          whereHelperint16
	NExtPoint5          whereHelperint16
	NExtPoint6          whereHelperint16
	NExtPoint7          whereHelperint16
	NUserIP             whereHelpernull_Int
	NUserIPPort         whereHelpernull_Int
	NFeeType            whereHelpernull_Int
	BParentalControl    whereHelperbool
	BIsBanned           whereHelperbool
	BIsUseOTP           whereHelperbool
	IOTPSessionLifeTime whereHelperint8
	IServiceFlag        whereHelperint
}{
	CAccName:            whereHelperstring{field: "[dbo].[Account_Info].[cAccName]"},
	CSecPassWord:        whereHelpernull_String{field: "[dbo].[Account_Info].[cSecPassWord]"},
	CPassWord:           whereHelperstring{field: "[dbo].[Account_Info].[cPassWord]"},
	IClientID:           whereHelpernull_Int64{field: "[dbo].[Account_Info].[iClientID]"},
	DLoginDate:          whereHelpernull_Time{field: "[dbo].[Account_Info].[dLoginDate]"},
	DLogoutDate:         whereHelpernull_Time{field: "[dbo].[Account_Info].[dLogoutDate]"},
	NExtPoint:           whereHelperint16{field: "[dbo].[Account_Info].[nExtPoint]"},
	NExtPoint1:          whereHelperint16{field: "[dbo].[Account_Info].[nExtPoint1]"},
	NExtPoint2:          whereHelperint16{field: "[dbo].[Account_Info].[nExtPoint2]"},
	NExtPoint3:          whereHelperint16{field: "[dbo].[Account_Info].[nExtPoint3]"},
	NExtPoint4:          whereHelperint16{field: "[dbo].[Account_Info].[nExtPoint4]"},
	NExtPoint5:          whereHelperint16{field: "[dbo].[Account_Info].[nExtPoint5]"},
	NExtPoint6:          whereHelperint16{field: "[dbo].[Account_Info].[nExtPoint6]"},
	NExtPoint7:          whereHelperint16{field: "[dbo].[Account_Info].[nExtPoint7]"},
	NUserIP:             whereHelpernull_Int{field: "[dbo].[Account_Info].[nUserIP]"},
	NUserIPPort:         whereHelpernull_Int{field: "[dbo].[Account_Info].[nUserIPPort]"},
	NFeeType:            whereHelpernull_Int{field: "[dbo].[Account_Info].[nFeeType]"},
	BParentalControl:    whereHelperbool{field: "[dbo].[Account_Info].[bParentalControl]"},
	BIsBanned:           whereHelperbool{field: "[dbo].[Account_Info].[bIsBanned]"},
	BIsUseOTP:           whereHelperbool{field: "[dbo].[Account_Info].[bIsUseOTP]"},
	IOTPSessionLifeTime: whereHelperint8{field: "[dbo].[Account_Info].[iOTPSessionLifeTime]"},
	IServiceFlag:        whereHelperint{field: "[dbo].[Account_Info].[iServiceFlag]"},
}

// AccountInfoRels is where relationship names are stored.
var AccountInfoRels = struct {
}{}

// accountInfoR is where relationships are stored.
type accountInfoR struct {
}

// NewStruct creates a new relationship struct
func (*accountInfoR) NewStruct() *accountInfoR {
	return &accountInfoR{}
}

// accountInfoL is where Load methods for each relationship are stored.
type accountInfoL struct{}

var (
	accountInfoAllColumns            = []string{"cAccName", "cSecPassWord", "cPassWord", "iClientID", "dLoginDate", "dLogoutDate", "nExtPoint", "nExtPoint1", "nExtPoint2", "nExtPoint3", "nExtPoint4", "nExtPoint5", "nExtPoint6", "nExtPoint7", "nUserIP", "nUserIPPort", "nFeeType", "bParentalControl", "bIsBanned", "bIsUseOTP", "iOTPSessionLifeTime", "iServiceFlag"}
	accountInfoColumnsWithoutDefault = []string{"cAccName", "cSecPassWord", "cPassWord", "iClientID", "dLoginDate", "dLogoutDate", "nExtPoint", "nExtPoint1", "nExtPoint2", "nExtPoint3", "nExtPoint4", "nExtPoint5", "nExtPoint6", "nExtPoint7", "nUserIP", "nUserIPPort", "nFeeType"}
	accountInfoColumnsWithDefault    = []string{"bParentalControl", "bIsBanned", "bIsUseOTP", "iOTPSessionLifeTime", "iServiceFlag"}
	accountInfoPrimaryKeyColumns     = []string{"cAccName"}
	accountInfoGeneratedColumns      = []string{}
)

type (
	// AccountInfoSlice is an alias for a slice of pointers to AccountInfo.
	// This should almost always be used instead of []AccountInfo.
	AccountInfoSlice []*AccountInfo

	accountInfoQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	accountInfoType                 = reflect.TypeOf(&AccountInfo{})
	accountInfoMapping              = queries.MakeStructMapping(accountInfoType)
	accountInfoPrimaryKeyMapping, _ = queries.BindMapping(accountInfoType, accountInfoMapping, accountInfoPrimaryKeyColumns)
	accountInfoInsertCacheMut       sync.RWMutex
	accountInfoInsertCache          = make(map[string]insertCache)
	accountInfoUpdateCacheMut       sync.RWMutex
	accountInfoUpdateCache          = make(map[string]updateCache)
	accountInfoUpsertCacheMut       sync.RWMutex
	accountInfoUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single accountInfo record from the query.
func (q accountInfoQuery) One(ctx context.Context, exec boil.ContextExecutor) (*AccountInfo, error) {
	o := &AccountInfo{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for Account_Info")
	}

	return o, nil
}

// All returns all AccountInfo records from the query.
func (q accountInfoQuery) All(ctx context.Context, exec boil.ContextExecutor) (AccountInfoSlice, error) {
	var o []*AccountInfo

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to AccountInfo slice")
	}

	return o, nil
}

// Count returns the count of all AccountInfo records in the query.
func (q accountInfoQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count Account_Info rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q accountInfoQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if Account_Info exists")
	}

	return count > 0, nil
}

// AccountInfos retrieves all the records using an executor.
func AccountInfos(mods ...qm.QueryMod) accountInfoQuery {
	mods = append(mods, qm.From("[dbo].[Account_Info]"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"[dbo].[Account_Info].*"})
	}

	return accountInfoQuery{q}
}

// FindAccountInfo retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAccountInfo(ctx context.Context, exec boil.ContextExecutor, cAccName string, selectCols ...string) (*AccountInfo, error) {
	accountInfoObj := &AccountInfo{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from [dbo].[Account_Info] where [cAccName]=$1", sel,
	)

	q := queries.Raw(query, cAccName)

	err := q.Bind(ctx, exec, accountInfoObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from Account_Info")
	}

	return accountInfoObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *AccountInfo) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no Account_Info provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(accountInfoColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	accountInfoInsertCacheMut.RLock()
	cache, cached := accountInfoInsertCache[key]
	accountInfoInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			accountInfoAllColumns,
			accountInfoColumnsWithDefault,
			accountInfoColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(accountInfoType, accountInfoMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(accountInfoType, accountInfoMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO [dbo].[Account_Info] ([%s]) %%sVALUES (%s)%%s", strings.Join(wl, "],["), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO [dbo].[Account_Info] %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryOutput = fmt.Sprintf("OUTPUT INSERTED.[%s] ", strings.Join(returnColumns, "],INSERTED.["))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into Account_Info")
	}

	if !cached {
		accountInfoInsertCacheMut.Lock()
		accountInfoInsertCache[key] = cache
		accountInfoInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the AccountInfo.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *AccountInfo) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	accountInfoUpdateCacheMut.RLock()
	cache, cached := accountInfoUpdateCache[key]
	accountInfoUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			accountInfoAllColumns,
			accountInfoPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update Account_Info, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE [dbo].[Account_Info] SET %s WHERE %s",
			strmangle.SetParamNames("[", "]", 1, wl),
			strmangle.WhereClause("[", "]", len(wl)+1, accountInfoPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(accountInfoType, accountInfoMapping, append(wl, accountInfoPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update Account_Info row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for Account_Info")
	}

	if !cached {
		accountInfoUpdateCacheMut.Lock()
		accountInfoUpdateCache[key] = cache
		accountInfoUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q accountInfoQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for Account_Info")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for Account_Info")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AccountInfoSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountInfoPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE [dbo].[Account_Info] SET %s WHERE %s",
		strmangle.SetParamNames("[", "]", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, accountInfoPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in accountInfo slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all accountInfo")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *AccountInfo) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no Account_Info provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(accountInfoColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	accountInfoUpsertCacheMut.RLock()
	cache, cached := accountInfoUpsertCache[key]
	accountInfoUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			accountInfoAllColumns,
			accountInfoColumnsWithDefault,
			accountInfoColumnsWithoutDefault,
			nzDefaults,
		)

		for i, v := range insert {
			if strmangle.ContainsAny(accountInfoPrimaryKeyColumns, v) && strmangle.ContainsAny(accountInfoColumnsWithDefault, v) {
				insert = append(insert[:i], insert[i+1:]...)
			}
		}
		if len(insert) == 0 {
			return errors.New("models: unable to upsert Account_Info, could not build insert column list")
		}

		update := updateColumns.UpdateColumnSet(
			accountInfoAllColumns,
			accountInfoPrimaryKeyColumns,
		)

		ret := strmangle.SetComplement(accountInfoAllColumns, strmangle.SetIntersect(insert, update))

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert Account_Info, could not build update column list")
		}

		cache.query = buildUpsertQueryMSSQL(dialect, "[dbo].[Account_Info]", accountInfoPrimaryKeyColumns, update, insert, ret)

		whitelist := make([]string, len(accountInfoPrimaryKeyColumns))
		copy(whitelist, accountInfoPrimaryKeyColumns)
		whitelist = append(whitelist, update...)
		whitelist = append(whitelist, insert...)

		cache.valueMapping, err = queries.BindMapping(accountInfoType, accountInfoMapping, whitelist)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(accountInfoType, accountInfoMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // MSSQL doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert Account_Info")
	}

	if !cached {
		accountInfoUpsertCacheMut.Lock()
		accountInfoUpsertCache[key] = cache
		accountInfoUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single AccountInfo record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *AccountInfo) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no AccountInfo provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), accountInfoPrimaryKeyMapping)
	sql := "DELETE FROM [dbo].[Account_Info] WHERE [cAccName]=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from Account_Info")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for Account_Info")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q accountInfoQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no accountInfoQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from Account_Info")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for Account_Info")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AccountInfoSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountInfoPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM [dbo].[Account_Info] WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, accountInfoPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from accountInfo slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for Account_Info")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *AccountInfo) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindAccountInfo(ctx, exec, o.CAccName)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AccountInfoSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := AccountInfoSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountInfoPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT [dbo].[Account_Info].* FROM [dbo].[Account_Info] WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, accountInfoPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in AccountInfoSlice")
	}

	*o = slice

	return nil
}

// AccountInfoExists checks if the AccountInfo row exists.
func AccountInfoExists(ctx context.Context, exec boil.ContextExecutor, cAccName string) (bool, error) {
	var exists bool
	sql := "select case when exists(select top(1) 1 from [dbo].[Account_Info] where [cAccName]=$1) then 1 else 0 end"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, cAccName)
	}
	row := exec.QueryRowContext(ctx, sql, cAccName)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if Account_Info exists")
	}

	return exists, nil
}

// Exists checks if the AccountInfo row exists.
func (o *AccountInfo) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return AccountInfoExists(ctx, exec, o.CAccName)
}
