// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AccountHabitus string
	AccountInfo    string
	AccountInfo2   string
	GMUserRoles    string
	GMUsers        string
}{
	AccountHabitus: "Account_Habitus",
	AccountInfo:    "Account_Info",
	AccountInfo2:   "Account_Info2",
	GMUserRoles:    "gm_user_roles",
	GMUsers:        "gm_users",
}
