// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// GMUserRole is an object representing the database table.
type GMUserRole struct {
	Username string `boil:"username" json:"username" toml:"username" yaml:"username"`
	RoleName string `boil:"role_name" json:"role_name" toml:"role_name" yaml:"role_name"`

	R *gmUserRoleR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L gmUserRoleL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var GMUserRoleColumns = struct {
	Username string
	RoleName string
}{
	Username: "username",
	RoleName: "role_name",
}

var GMUserRoleTableColumns = struct {
	Username string
	RoleName string
}{
	Username: "gm_user_roles.username",
	RoleName: "gm_user_roles.role_name",
}

// Generated where

var GMUserRoleWhere = struct {
	Username whereHelperstring
	RoleName whereHelperstring
}{
	Username: whereHelperstring{field: "[dbo].[gm_user_roles].[username]"},
	RoleName: whereHelperstring{field: "[dbo].[gm_user_roles].[role_name]"},
}

// GMUserRoleRels is where relationship names are stored.
var GMUserRoleRels = struct {
	UsernameGMUser string
}{
	UsernameGMUser: "UsernameGMUser",
}

// gmUserRoleR is where relationships are stored.
type gmUserRoleR struct {
	UsernameGMUser *GMUser `boil:"UsernameGMUser" json:"UsernameGMUser" toml:"UsernameGMUser" yaml:"UsernameGMUser"`
}

// NewStruct creates a new relationship struct
func (*gmUserRoleR) NewStruct() *gmUserRoleR {
	return &gmUserRoleR{}
}

func (o *GMUserRole) GetUsernameGMUser() *GMUser {
	if o == nil {
		return nil
	}

	return o.R.GetUsernameGMUser()
}

func (r *gmUserRoleR) GetUsernameGMUser() *GMUser {
	if r == nil {
		return nil
	}

	return r.UsernameGMUser
}

// gmUserRoleL is where Load methods for each relationship are stored.
type gmUserRoleL struct{}

var (
	gmUserRoleAllColumns            = []string{"username", "role_name"}
	gmUserRoleColumnsWithoutDefault = []string{"username", "role_name"}
	gmUserRoleColumnsWithDefault    = []string{}
	gmUserRolePrimaryKeyColumns     = []string{"username", "role_name"}
	gmUserRoleGeneratedColumns      = []string{}
)

type (
	// GMUserRoleSlice is an alias for a slice of pointers to GMUserRole.
	// This should almost always be used instead of []GMUserRole.
	GMUserRoleSlice []*GMUserRole

	gmUserRoleQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	gmUserRoleType                 = reflect.TypeOf(&GMUserRole{})
	gmUserRoleMapping              = queries.MakeStructMapping(gmUserRoleType)
	gmUserRolePrimaryKeyMapping, _ = queries.BindMapping(gmUserRoleType, gmUserRoleMapping, gmUserRolePrimaryKeyColumns)
	gmUserRoleInsertCacheMut       sync.RWMutex
	gmUserRoleInsertCache          = make(map[string]insertCache)
	gmUserRoleUpdateCacheMut       sync.RWMutex
	gmUserRoleUpdateCache          = make(map[string]updateCache)
	gmUserRoleUpsertCacheMut       sync.RWMutex
	gmUserRoleUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single gmUserRole record from the query.
func (q gmUserRoleQuery) One(ctx context.Context, exec boil.ContextExecutor) (*GMUserRole, error) {
	o := &GMUserRole{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for gm_user_roles")
	}

	return o, nil
}

// All returns all GMUserRole records from the query.
func (q gmUserRoleQuery) All(ctx context.Context, exec boil.ContextExecutor) (GMUserRoleSlice, error) {
	var o []*GMUserRole

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to GMUserRole slice")
	}

	return o, nil
}

// Count returns the count of all GMUserRole records in the query.
func (q gmUserRoleQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count gm_user_roles rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q gmUserRoleQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if gm_user_roles exists")
	}

	return count > 0, nil
}

// UsernameGMUser pointed to by the foreign key.
func (o *GMUserRole) UsernameGMUser(mods ...qm.QueryMod) gmUserQuery {
	queryMods := []qm.QueryMod{
		qm.Where("[username] = ?", o.Username),
	}

	queryMods = append(queryMods, mods...)

	return GMUsers(queryMods...)
}

// LoadUsernameGMUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (gmUserRoleL) LoadUsernameGMUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeGMUserRole any, mods queries.Applicator) error {
	var slice []*GMUserRole
	var object *GMUserRole

	if singular {
		var ok bool
		object, ok = maybeGMUserRole.(*GMUserRole)
		if !ok {
			object = new(GMUserRole)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeGMUserRole)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeGMUserRole))
			}
		}
	} else {
		s, ok := maybeGMUserRole.(*[]*GMUserRole)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeGMUserRole)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeGMUserRole))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &gmUserRoleR{}
		}
		args[object.Username] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &gmUserRoleR{}
			}

			args[obj.Username] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`dbo.gm_users`),
		qm.WhereIn(`dbo.gm_users.username in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load GMUser")
	}

	var resultSlice []*GMUser
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice GMUser")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for gm_users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for gm_users")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.UsernameGMUser = foreign
		if foreign.R == nil {
			foreign.R = &gmUserR{}
		}
		foreign.R.UsernameGMUserRoles = append(foreign.R.UsernameGMUserRoles, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.Username == foreign.Username {
				local.R.UsernameGMUser = foreign
				if foreign.R == nil {
					foreign.R = &gmUserR{}
				}
				foreign.R.UsernameGMUserRoles = append(foreign.R.UsernameGMUserRoles, local)
				break
			}
		}
	}

	return nil
}

// SetUsernameGMUser of the gmUserRole to the related item.
// Sets o.R.UsernameGMUser to related.
// Adds o to related.R.UsernameGMUserRoles.
func (o *GMUserRole) SetUsernameGMUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *GMUser) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE [dbo].[gm_user_roles] SET %s WHERE %s",
		strmangle.SetParamNames("[", "]", 1, []string{"username"}),
		strmangle.WhereClause("[", "]", 2, gmUserRolePrimaryKeyColumns),
	)
	values := []any{related.Username, o.Username, o.RoleName}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.Username = related.Username
	if o.R == nil {
		o.R = &gmUserRoleR{
			UsernameGMUser: related,
		}
	} else {
		o.R.UsernameGMUser = related
	}

	if related.R == nil {
		related.R = &gmUserR{
			UsernameGMUserRoles: GMUserRoleSlice{o},
		}
	} else {
		related.R.UsernameGMUserRoles = append(related.R.UsernameGMUserRoles, o)
	}

	return nil
}

// GMUserRoles retrieves all the records using an executor.
func GMUserRoles(mods ...qm.QueryMod) gmUserRoleQuery {
	mods = append(mods, qm.From("[dbo].[gm_user_roles]"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"[dbo].[gm_user_roles].*"})
	}

	return gmUserRoleQuery{q}
}

// FindGMUserRole retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindGMUserRole(ctx context.Context, exec boil.ContextExecutor, username string, roleName string, selectCols ...string) (*GMUserRole, error) {
	gmUserRoleObj := &GMUserRole{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from [dbo].[gm_user_roles] where [username]=$1 AND [role_name]=$2", sel,
	)

	q := queries.Raw(query, username, roleName)

	err := q.Bind(ctx, exec, gmUserRoleObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from gm_user_roles")
	}

	return gmUserRoleObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *GMUserRole) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no gm_user_roles provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(gmUserRoleColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	gmUserRoleInsertCacheMut.RLock()
	cache, cached := gmUserRoleInsertCache[key]
	gmUserRoleInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			gmUserRoleAllColumns,
			gmUserRoleColumnsWithDefault,
			gmUserRoleColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(gmUserRoleType, gmUserRoleMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(gmUserRoleType, gmUserRoleMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO [dbo].[gm_user_roles] ([%s]) %%sVALUES (%s)%%s", strings.Join(wl, "],["), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO [dbo].[gm_user_roles] %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryOutput = fmt.Sprintf("OUTPUT INSERTED.[%s] ", strings.Join(returnColumns, "],INSERTED.["))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into gm_user_roles")
	}

	if !cached {
		gmUserRoleInsertCacheMut.Lock()
		gmUserRoleInsertCache[key] = cache
		gmUserRoleInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the GMUserRole.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *GMUserRole) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	gmUserRoleUpdateCacheMut.RLock()
	cache, cached := gmUserRoleUpdateCache[key]
	gmUserRoleUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			gmUserRoleAllColumns,
			gmUserRolePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update gm_user_roles, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE [dbo].[gm_user_roles] SET %s WHERE %s",
			strmangle.SetParamNames("[", "]", 1, wl),
			strmangle.WhereClause("[", "]", len(wl)+1, gmUserRolePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(gmUserRoleType, gmUserRoleMapping, append(wl, gmUserRolePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update gm_user_roles row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for gm_user_roles")
	}

	if !cached {
		gmUserRoleUpdateCacheMut.Lock()
		gmUserRoleUpdateCache[key] = cache
		gmUserRoleUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q gmUserRoleQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for gm_user_roles")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for gm_user_roles")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o GMUserRoleSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), gmUserRolePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE [dbo].[gm_user_roles] SET %s WHERE %s",
		strmangle.SetParamNames("[", "]", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, gmUserRolePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in gmUserRole slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all gmUserRole")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *GMUserRole) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no gm_user_roles provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(gmUserRoleColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	gmUserRoleUpsertCacheMut.RLock()
	cache, cached := gmUserRoleUpsertCache[key]
	gmUserRoleUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			gmUserRoleAllColumns,
			gmUserRoleColumnsWithDefault,
			gmUserRoleColumnsWithoutDefault,
			nzDefaults,
		)

		for i, v := range insert {
			if strmangle.ContainsAny(gmUserRolePrimaryKeyColumns, v) && strmangle.ContainsAny(gmUserRoleColumnsWithDefault, v) {
				insert = append(insert[:i], insert[i+1:]...)
			}
		}
		if len(insert) == 0 {
			return errors.New("models: unable to upsert gm_user_roles, could not build insert column list")
		}

		update := updateColumns.UpdateColumnSet(
			gmUserRoleAllColumns,
			gmUserRolePrimaryKeyColumns,
		)

		ret := strmangle.SetComplement(gmUserRoleAllColumns, strmangle.SetIntersect(insert, update))

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert gm_user_roles, could not build update column list")
		}

		cache.query = buildUpsertQueryMSSQL(dialect, "[dbo].[gm_user_roles]", gmUserRolePrimaryKeyColumns, update, insert, ret)

		whitelist := make([]string, len(gmUserRolePrimaryKeyColumns))
		copy(whitelist, gmUserRolePrimaryKeyColumns)
		whitelist = append(whitelist, update...)
		whitelist = append(whitelist, insert...)

		cache.valueMapping, err = queries.BindMapping(gmUserRoleType, gmUserRoleMapping, whitelist)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(gmUserRoleType, gmUserRoleMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // MSSQL doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert gm_user_roles")
	}

	if !cached {
		gmUserRoleUpsertCacheMut.Lock()
		gmUserRoleUpsertCache[key] = cache
		gmUserRoleUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single GMUserRole record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *GMUserRole) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no GMUserRole provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), gmUserRolePrimaryKeyMapping)
	sql := "DELETE FROM [dbo].[gm_user_roles] WHERE [username]=$1 AND [role_name]=$2"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from gm_user_roles")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for gm_user_roles")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q gmUserRoleQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no gmUserRoleQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from gm_user_roles")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for gm_user_roles")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o GMUserRoleSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), gmUserRolePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM [dbo].[gm_user_roles] WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, gmUserRolePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from gmUserRole slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for gm_user_roles")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *GMUserRole) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindGMUserRole(ctx, exec, o.Username, o.RoleName)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *GMUserRoleSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := GMUserRoleSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), gmUserRolePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT [dbo].[gm_user_roles].* FROM [dbo].[gm_user_roles] WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, gmUserRolePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in GMUserRoleSlice")
	}

	*o = slice

	return nil
}

// GMUserRoleExists checks if the GMUserRole row exists.
func GMUserRoleExists(ctx context.Context, exec boil.ContextExecutor, username string, roleName string) (bool, error) {
	var exists bool
	sql := "select case when exists(select top(1) 1 from [dbo].[gm_user_roles] where [username]=$1 AND [role_name]=$2) then 1 else 0 end"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, username, roleName)
	}
	row := exec.QueryRowContext(ctx, sql, username, roleName)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if gm_user_roles exists")
	}

	return exists, nil
}

// Exists checks if the GMUserRole row exists.
func (o *GMUserRole) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return GMUserRoleExists(ctx, exec, o.Username, o.RoleName)
}
