// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// GMUser is an object representing the database table.
type GMUser struct {
	Username     string    `boil:"username" json:"username" toml:"username" yaml:"username"`
	PasswordHash string    `boil:"password_hash" json:"password_hash" toml:"password_hash" yaml:"password_hash"`
	IsActive     bool      `boil:"is_active" json:"is_active" toml:"is_active" yaml:"is_active"`
	CreatedAt    time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *gmUserR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L gmUserL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var GMUserColumns = struct {
	Username     string
	PasswordHash string
	IsActive     string
	CreatedAt    string
}{
	Username:     "username",
	PasswordHash: "password_hash",
	IsActive:     "is_active",
	CreatedAt:    "created_at",
}

var GMUserTableColumns = struct {
	Username     string
	PasswordHash string
	IsActive     string
	CreatedAt    string
}{
	Username:     "gm_users.username",
	PasswordHash: "gm_users.password_hash",
	IsActive:     "gm_users.is_active",
	CreatedAt:    "gm_users.created_at",
}

// Generated where

var GMUserWhere = struct {
	Username     whereHelperstring
	PasswordHash whereHelperstring
	IsActive     whereHelperbool
	CreatedAt    whereHelpertime_Time
}{
	Username:     whereHelperstring{field: "[dbo].[gm_users].[username]"},
	PasswordHash: whereHelperstring{field: "[dbo].[gm_users].[password_hash]"},
	IsActive:     whereHelperbool{field: "[dbo].[gm_users].[is_active]"},
	CreatedAt:    whereHelpertime_Time{field: "[dbo].[gm_users].[created_at]"},
}

// GMUserRels is where relationship names are stored.
var GMUserRels = struct {
	UsernameGMUserRoles string
}{
	UsernameGMUserRoles: "UsernameGMUserRoles",
}

// gmUserR is where relationships are stored.
type gmUserR struct {
	UsernameGMUserRoles GMUserRoleSlice `boil:"UsernameGMUserRoles" json:"UsernameGMUserRoles" toml:"UsernameGMUserRoles" yaml:"UsernameGMUserRoles"`
}

// NewStruct creates a new relationship struct
func (*gmUserR) NewStruct() *gmUserR {
	return &gmUserR{}
}

func (o *GMUser) GetUsernameGMUserRoles() GMUserRoleSlice {
	if o == nil {
		return nil
	}

	return o.R.GetUsernameGMUserRoles()
}

func (r *gmUserR) GetUsernameGMUserRoles() GMUserRoleSlice {
	if r == nil {
		return nil
	}

	return r.UsernameGMUserRoles
}

// gmUserL is where Load methods for each relationship are stored.
type gmUserL struct{}

var (
	gmUserAllColumns            = []string{"username", "password_hash", "is_active", "created_at"}
	gmUserColumnsWithoutDefault = []string{"username", "password_hash"}
	gmUserColumnsWithDefault    = []string{"is_active", "created_at"}
	gmUserPrimaryKeyColumns     = []string{"username"}
	gmUserGeneratedColumns      = []string{}
)

type (
	// GMUserSlice is an alias for a slice of pointers to GMUser.
	// This should almost always be used instead of []GMUser.
	GMUserSlice []*GMUser

	gmUserQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	gmUserType                 = reflect.TypeOf(&GMUser{})
	gmUserMapping              = queries.MakeStructMapping(gmUserType)
	gmUserPrimaryKeyMapping, _ = queries.BindMapping(gmUserType, gmUserMapping, gmUserPrimaryKeyColumns)
	gmUserInsertCacheMut       sync.RWMutex
	gmUserInsertCache          = make(map[string]insertCache)
	gmUserUpdateCacheMut       sync.RWMutex
	gmUserUpdateCache          = make(map[string]updateCache)
	gmUserUpsertCacheMut       sync.RWMutex
	gmUserUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single gmUser record from the query.
func (q gmUserQuery) One(ctx context.Context, exec boil.ContextExecutor) (*GMUser, error) {
	o := &GMUser{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for gm_users")
	}

	return o, nil
}

// All returns all GMUser records from the query.
func (q gmUserQuery) All(ctx context.Context, exec boil.ContextExecutor) (GMUserSlice, error) {
	var o []*GMUser

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to GMUser slice")
	}

	return o, nil
}

// Count returns the count of all GMUser records in the query.
func (q gmUserQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count gm_users rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q gmUserQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if gm_users exists")
	}

	return count > 0, nil
}

// UsernameGMUserRoles retrieves all the gm_user_role's GMUserRoles with an executor via username column.
func (o *GMUser) UsernameGMUserRoles(mods ...qm.QueryMod) gmUserRoleQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("[dbo].[gm_user_roles].[username]=?", o.Username),
	)

	return GMUserRoles(queryMods...)
}

// LoadUsernameGMUserRoles allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (gmUserL) LoadUsernameGMUserRoles(ctx context.Context, e boil.ContextExecutor, singular bool, maybeGMUser any, mods queries.Applicator) error {
	var slice []*GMUser
	var object *GMUser

	if singular {
		var ok bool
		object, ok = maybeGMUser.(*GMUser)
		if !ok {
			object = new(GMUser)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeGMUser)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeGMUser))
			}
		}
	} else {
		s, ok := maybeGMUser.(*[]*GMUser)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeGMUser)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeGMUser))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &gmUserR{}
		}
		args[object.Username] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &gmUserR{}
			}
			args[obj.Username] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`dbo.gm_user_roles`),
		qm.WhereIn(`dbo.gm_user_roles.username in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load gm_user_roles")
	}

	var resultSlice []*GMUserRole
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice gm_user_roles")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on gm_user_roles")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for gm_user_roles")
	}

	if singular {
		object.R.UsernameGMUserRoles = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &gmUserRoleR{}
			}
			foreign.R.UsernameGMUser = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.Username == foreign.Username {
				local.R.UsernameGMUserRoles = append(local.R.UsernameGMUserRoles, foreign)
				if foreign.R == nil {
					foreign.R = &gmUserRoleR{}
				}
				foreign.R.UsernameGMUser = local
				break
			}
		}
	}

	return nil
}

// AddUsernameGMUserRoles adds the given related objects to the existing relationships
// of the gm_user, optionally inserting them as new records.
// Appends related to o.R.UsernameGMUserRoles.
// Sets related.R.UsernameGMUser appropriately.
func (o *GMUser) AddUsernameGMUserRoles(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*GMUserRole) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.Username = o.Username
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE [dbo].[gm_user_roles] SET %s WHERE %s",
				strmangle.SetParamNames("[", "]", 1, []string{"username"}),
				strmangle.WhereClause("[", "]", 2, gmUserRolePrimaryKeyColumns),
			)
			values := []any{o.Username, rel.Username, rel.RoleName}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.Username = o.Username
		}
	}

	if o.R == nil {
		o.R = &gmUserR{
			UsernameGMUserRoles: related,
		}
	} else {
		o.R.UsernameGMUserRoles = append(o.R.UsernameGMUserRoles, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &gmUserRoleR{
				UsernameGMUser: o,
			}
		} else {
			rel.R.UsernameGMUser = o
		}
	}
	return nil
}

// GMUsers retrieves all the records using an executor.
func GMUsers(mods ...qm.QueryMod) gmUserQuery {
	mods = append(mods, qm.From("[dbo].[gm_users]"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"[dbo].[gm_users].*"})
	}

	return gmUserQuery{q}
}

// FindGMUser retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindGMUser(ctx context.Context, exec boil.ContextExecutor, username string, selectCols ...string) (*GMUser, error) {
	gmUserObj := &GMUser{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from [dbo].[gm_users] where [username]=$1", sel,
	)

	q := queries.Raw(query, username)

	err := q.Bind(ctx, exec, gmUserObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from gm_users")
	}

	return gmUserObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *GMUser) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no gm_users provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(gmUserColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	gmUserInsertCacheMut.RLock()
	cache, cached := gmUserInsertCache[key]
	gmUserInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			gmUserAllColumns,
			gmUserColumnsWithDefault,
			gmUserColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(gmUserType, gmUserMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(gmUserType, gmUserMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO [dbo].[gm_users] ([%s]) %%sVALUES (%s)%%s", strings.Join(wl, "],["), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO [dbo].[gm_users] %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryOutput = fmt.Sprintf("OUTPUT INSERTED.[%s] ", strings.Join(returnColumns, "],INSERTED.["))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into gm_users")
	}

	if !cached {
		gmUserInsertCacheMut.Lock()
		gmUserInsertCache[key] = cache
		gmUserInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the GMUser.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *GMUser) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	gmUserUpdateCacheMut.RLock()
	cache, cached := gmUserUpdateCache[key]
	gmUserUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			gmUserAllColumns,
			gmUserPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update gm_users, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE [dbo].[gm_users] SET %s WHERE %s",
			strmangle.SetParamNames("[", "]", 1, wl),
			strmangle.WhereClause("[", "]", len(wl)+1, gmUserPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(gmUserType, gmUserMapping, append(wl, gmUserPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update gm_users row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for gm_users")
	}

	if !cached {
		gmUserUpdateCacheMut.Lock()
		gmUserUpdateCache[key] = cache
		gmUserUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q gmUserQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for gm_users")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for gm_users")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o GMUserSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), gmUserPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE [dbo].[gm_users] SET %s WHERE %s",
		strmangle.SetParamNames("[", "]", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, gmUserPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in gmUser slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all gmUser")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *GMUser) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no gm_users provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(gmUserColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	gmUserUpsertCacheMut.RLock()
	cache, cached := gmUserUpsertCache[key]
	gmUserUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			gmUserAllColumns,
			gmUserColumnsWithDefault,
			gmUserColumnsWithoutDefault,
			nzDefaults,
		)

		for i, v := range insert {
			if strmangle.ContainsAny(gmUserPrimaryKeyColumns, v) && strmangle.ContainsAny(gmUserColumnsWithDefault, v) {
				insert = append(insert[:i], insert[i+1:]...)
			}
		}
		if len(insert) == 0 {
			return errors.New("models: unable to upsert gm_users, could not build insert column list")
		}

		update := updateColumns.UpdateColumnSet(
			gmUserAllColumns,
			gmUserPrimaryKeyColumns,
		)

		ret := strmangle.SetComplement(gmUserAllColumns, strmangle.SetIntersect(insert, update))

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert gm_users, could not build update column list")
		}

		cache.query = buildUpsertQueryMSSQL(dialect, "[dbo].[gm_users]", gmUserPrimaryKeyColumns, update, insert, ret)

		whitelist := make([]string, len(gmUserPrimaryKeyColumns))
		copy(whitelist, gmUserPrimaryKeyColumns)
		whitelist = append(whitelist, update...)
		whitelist = append(whitelist, insert...)

		cache.valueMapping, err = queries.BindMapping(gmUserType, gmUserMapping, whitelist)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(gmUserType, gmUserMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // MSSQL doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert gm_users")
	}

	if !cached {
		gmUserUpsertCacheMut.Lock()
		gmUserUpsertCache[key] = cache
		gmUserUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single GMUser record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *GMUser) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no GMUser provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), gmUserPrimaryKeyMapping)
	sql := "DELETE FROM [dbo].[gm_users] WHERE [username]=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from gm_users")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for gm_users")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q gmUserQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no gmUserQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from gm_users")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for gm_users")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o GMUserSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), gmUserPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM [dbo].[gm_users] WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, gmUserPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from gmUser slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for gm_users")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *GMUser) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindGMUser(ctx, exec, o.Username)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *GMUserSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := GMUserSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), gmUserPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT [dbo].[gm_users].* FROM [dbo].[gm_users] WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, gmUserPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in GMUserSlice")
	}

	*o = slice

	return nil
}

// GMUserExists checks if the GMUser row exists.
func GMUserExists(ctx context.Context, exec boil.ContextExecutor, username string) (bool, error) {
	var exists bool
	sql := "select case when exists(select top(1) 1 from [dbo].[gm_users] where [username]=$1) then 1 else 0 end"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, username)
	}
	row := exec.QueryRowContext(ctx, sql, username)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if gm_users exists")
	}

	return exists, nil
}

// Exists checks if the GMUser row exists.
func (o *GMUser) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return GMUserExists(ctx, exec, o.Username)
}
